#!/bin/bash

# GUI only on desktop editions.
if type gnome-shell &> /dev/null; then
    # Package dbus-x11 is needed for GUI root scripts, e.g. kz-install.
    apt-get install --yes dbus-x11 zenity
fi

if ! type fuser &> /dev/null; then
    apt-get install --yes psmisc
fi

if ! snap list core &> /dev/null; then
    systemctl enable --now snapd.socket
    systemctl restart snapd.seeded.service
    snap install core
fi

true
