#!/usr/bin/bash

# GUI only on desktop.
if type gnome-shell &> /dev/null; then
    apt-get install --yes zenity
fi

# Snap install mainly for Debian.
if ! snap list core &> /dev/null; then
    systemctl enable --now snapd.socket
    systemctl restart snapd.seeded.service
    snap install core
fi

exit 0
