#!/usr/bin/bash

###############################################################################
# SPDX-FileComment: postinst script for Debian package kz
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################

# Snap installation is mainly done for Debian.
if ! snap list core &> /dev/null; then
    systemctl enable --now snapd.socket
    systemctl restart snapd.seeded.service
    snap install core
fi

exit 0