#!/usr/bin/env bash
###############################################################################
# SPDX-FileComment: Post-install script for Debian package kz
#
# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
# SPDX-License-Identifier: CC0-1.0
###############################################################################
set -o errexit

# For older distro like Ubuntu 18.04.
[[ -f /usr/bin/bash ]] ||  sudo ln --symbolic /bin/bash /usr/bin/bash

exit 0
