#!/bin/bash

# preinst script for kz

set -e

# -----------------------------------------------------------------------------
# Add components to package sources if on Debian.
# -----------------------------------------------------------------------------
if grep --quiet --regexp='Debian' /etc/os-release && [[ -f /etc/apt/sources.list ]]; then sudo sed --in-place --expression='s/main non-free-firmware/contrib main non-free non-free-firmware/' /etc/apt/sources.list; fi
if grep --quiet --regexp='Debian' /etc/os-release && [[ -f /etc/apt/debian.sources ]]; then sudo sed --in-place --expression='s/main non-free-firmware/contrib main non-free non-free-firmware/' /etc/apt/debian.sources; fi

exit 0
