#!/bin/bash

# Oude bestanden.
rm  --force                     \
    /root/kzlsinstalled-*       \
    /usr/local/etc/kz_*         \
    /usr/local/etc/kzbackup*    \
    /usr/local/etc/kzrestore*

# Oude mappen.
rm --force --recursive /opt/wallpapers

true
