#!/bin/bash

# Oude bestanden.
rm  --force                         \
    /root/kzlsinstalled-*           \
    /usr/local/etc/kzbackup*        \
    /usr/local/etc/kz_lsinstalled*  \
    /usr/local/etc/kzrestore*

# Oude mappen.
rm --force --recursive /opt/wallpapers

true
